### PR TITLE
57 ast approach

### LINKED ISSUE #57: Conditional includes
`if` and `unless` are useful in rules but get repetitive if multiple rules require the same condition:

```
package {
    ....
    if => equal("${ARCH}", "x86_64")
}
file {
    ....
    if => equal("${ARCH}", "x86_64")
}
file {
    ....
    if => equal("${ARCH}", "x86_64")
}
```

A nicer implementation might be to include files based on conditionals:
```
include "x86_64_stuff.txt" if equal("${ARCH}", "x86_64")
```
This could use the same conditionals that are available for rules.

Another alternative would be to allow wrapping `if` and `unless` around rules:
```
if equal("${ARCH}", "x86_64") {
    package {
        ....
    }

    # ${ARCH} equals "x86_64" and ${VAR} equals "foo"
    if equal("${VAR}", "foo") {
        file {
            ....
        }
    }
}
```

### PR DESCRIPTION
**Pull request by skx**
This pull-request significantly changes our interpreter to make it more akin to something traditional like an AST-walking interpreter.  (It isn't, but rather than processing just `Rule` objects we now have various node times the parser can product and the executor-module will interpret.)
    
This closes #57.

The big change here is that variable processing, string expansion, and file/rule-inclusion will happen at runtime rather than at parse-time - and our include-file handling has been updated to allow file inclusion to be _conditional_, much like our rules are.

The test-cases have been updated so they continue to pass, but more work should be done there to ensure we're functional.

**Regressions**

Temporarily backtick-expansion has been removed from parameter values - if you need to have a dynamic output in your value please use a variable.  Variable assignments continue to allow backticks.

### CODE REVIEW

**Comment by skx** [comment]
Next steps:

* Drop the environment from the parser
   * This means dropping the variable/command expansion we carry out.
   * NOTE: The ast.Assignment node needs to store _tokens_ not _Strings_
     * Otherwise we can't record "backtick" vs "string".
* Add the environment to the evaluator.
* Wire up the evaluator to process rules
  * Ignore parameter/variable/backtick expansion initially.
* Wire up the evaluator to process assignments.
* Wire up the evaluator to process include-files
  * Create a new parser.
  * Invoke it.
  * Recursively call the evaluator with the new rules.

**Comment by skx** [comment]
Managed to base this on the previous bad approach.  Too bad.  Will squash before I finally merge.

**Comment by skx** [comment]
@alexwhitman this needs to be updated so that the test-cases pass, but the core is solid and things _seem_ to work as expected.

Any testing you manage in the near future would be most welcome.

**Comment by alexwhitman** [comment]
Something is failing on in this but I don't get much info as to why. I have a simple file containing the following:
```
file {
        name => "file:user:gitconfig",
        source => "./files/home/__user__/_gitconfig",
        target => "${HOMEDIR}/.gitconfig",
        owner => "${USERNAME}",
        group => "${USERNAME}",
        mode => "0644",
}

file {
        name => "file:user:inputrc",
        source => "./files/home/__user__/_inputrc",
        target => "${HOMEDIR}/.inputrc",
        owner => "${USERNAME}",
        group => "${USERNAME}",
        mode => "0644",
}

directory {
       name => "directory:user:npm-global",
       target => "${HOMEDIR}/.npm-global",
       state => "present",
}

file {
        name => "file:user:npmrc",
        template => "./files/home/__user__/_npmrc",
        target => "${HOMEDIR}/.npmrc",
        owner => "${USERNAME}",
        group => "${USERNAME}",
        mode => "0644",
        require => "directory:user:npm-global",
}
```

The only output I get is below with a `0` exit code.
```
$ ./marionette -verbose ./user.rules 
Running file-module rule: file:user:gitconfig
```

**Comment by skx** [comment]
Stupidly I stopped running after the first rule.  Updated now to keep going, unless there are errors.

**Comment by alexwhitman** [comment]
That's fixed it. I'll give it some further testing tomorrow. Thanks for the quick work.

**Comment by alexwhitman** [comment]
There's an issue with variables in conditionals, at least for `include`. Take the following rules:
```
# test.txt

include "test-2.txt" if equal("${USERNAME}", "alex")

shell {
    name => "shell test",
    command => "echo ${USERNAME}",
}

# test-2.txt

shell {
    name => "shell test 2",
    command => "Hello from test-2",
}
```
`./marionette -verbose text.txt` gives the following output:
```
	Skipping inclusion of test-2.txt condition was not true: equal(${USERNAME},alex)
Running shell-module rule: shell test
	Executing: echo alex
alex
	Rule resulted in a change being made.
```

It looks like the conditional is comparing the string "${USERNAME}" rather than the value of the variable.

**Comment by skx** [comment]
That's a good catch, I wasn't expanding the variables in the arguments to the conditionals.

Resolved now.

Barring the regression relating to block-values having `backtick` commands in them I think I'm done now, unless you spot anything else.

**Comment by alexwhitman** [comment]
Yep, that works now. I'll do some further testing.

**Comment by alexwhitman** [comment]
It's possible to get stuck in an infinite loop when including files. Take
```
# test.txt

include "test2.txt"

# test2.txt

include test.txt
```

Now normally this wouldn't be a typical occurrence but could be possible with complex set ups. Running `marionette -verbose test.txt` produces no output, maxes out the CPU and doesn't exit.

**Comment by skx** [comment]
Resolved now, and updated the execution under `-verbose` to report more about what is going on.

**Comment by alexwhitman** [comment]
This no longer gets stuck in a loop but does execute the same rules multiple times.
```
# test.txt

include "test2.txt"

shell {
        name => "echo",
        command => "echo test",
}

# test2.txt

include test.txt
```
results in
```
Processing inclusion: &{<nil> test2.txt  <nil>}

Processing inclusion: &{<nil> test.txt  <nil>}

Processing inclusion: &{<nil> test2.txt  <nil>}

Skipping include file test2.txt - already seen

Processing rule: &{<nil> shell echo false map[command:echo test name:echo]}

Running shell-module rule: echo
        Executing: echo test
test
        Rule resulted in a change being made.
Processing rule: &{<nil> shell echo false map[command:echo test name:echo]}

Running shell-module rule: echo
        Executing: echo test
test
        Rule resulted in a change being made.
```

**Comment by skx** [comment]
I guess the difference there is the first file is loaded "manually",  so the main/initial file isn't regarded as already having been seen.

**Comment by skx** [comment]
(Guess this is a reminder to myself that I need to add more test-cases.  But I've updated to account for this omission anyway.)

**Comment by alexwhitman** [comment]
Seems to be working well now, thanks.

The `-verbose` output seems a bit messy now but that could be cleaned up later. I was thinking it would be nice to have different levels of output (info/error/debug etc) which could then be colored, timestamped etc all in a common place in a consistent manner, rather than `fmt` being called directly in modules and other areas but that's something possibly for another time.

**Comment by skx** [comment]
Agreed.

Better, more consistent, and more useful logging would be useful - but I'll file a new issue for that.

Will merge this later today.

**Pull request merged**
